### ISSUE TITLE
Navigating the dates with arrow keys

### ISSUE THREAD

**Issue by martinlex** [duetds/date-picker#13]
**Describe the bug**
I expected to be able to use all arrow keys to navigate within the dates.
Only up key and down key work fine.
The left key and right key will read out a digit, one digit at a time.
This is confusing for the user.

Using Win 10 with NVDA.

**Comment by WickyNilliams** [comment]
Forgive me if I'm wrong here, but isn't this the default mode of operation for NVDA? You need to switch to application mode (Insert + Space) to pass-through arrow keys. Or use the table navigation commands (alt + ctrl + arrow).

**Comment by ArnaudDelafosse** [comment]
That's correct. Up/Down arrows in linear mode (top left to bottom right) or Ctrl+Alt+(arrow) to navigate freely within a table.
@martinlex you've got a few keyboard shortcuts cheat sheets on the Web, like this one https://dequeuniversity.com/screenreaders/nvda-keyboard-shortcuts#nvda-tables

**Comment by WickyNilliams** [comment]
Yeah I'm pretty confident this is behaving as expected. Closing for now. Please say if you think this is a mistake
