### ISSUE TITLE
Default date is strange for future months

### ISSUE THREAD

**Issue by martinlex** [duetds/date-picker#14]
**Describe the bug**
When I navigate with keyboard, I open the date picker.
I go from date to year to next/prev month buttons.

When I leave the next/prev month buttons:
If it's the current month: the default focus is today's date (Sep 17th) - Correct
If it's any month in the future: the default focus is still today's date (= Oct 17th, Nov 17th etc)  - Seems strange
I think it would be better if the focus goes to the 1st.

**Comment by WickyNilliams** [comment]
I think this comes down to personal preference? Having checked a number of date pickers, seems like some move to first day of month (as you suggest), whilst most move to same day of month (as happens here).

I would personally say the current behaviour here fine, and at least consistent with most date pickers. Here are a bunch which follow the behaviour here:

* Native date picker in chrome & FF!
* [jQuery UI date picker](https://jqueryui.com/datepicker/#default)
* [Angular material date picker](https://material.angular.io/components/datepicker/overview)
* [Vaadin date picker](https://vaadin.com/components/vaadin-date-picker/html-examples)
* [Flatpickr](https://flatpickr.js.org/examples/)
* [React date picker](https://reactdatepicker.com/)
* [React dates (airbnb)](http://airbnb.io/react-dates/?path=/story/singledatepicker-sdp--default)

Would be interested to see any counter examples

**Comment by viljamis** [comment]
Hmm, I also agree with @WickyNilliams here. Would keep the behaviour as it is now.
