### ISSUE TITLE
editing in the middle of the text moves cursor to end (in Safari)

### ISSUE THREAD

**Issue by Haroenv** [duetds/date-picker#17]
**Describe the bug**

When the cursor is in the middle of the text, and you type, the cursor jumps to the end. This is likely because of setting the value without changing the "selection"

**To Reproduce**
1. type part of a date
2. move your cursor to somewhere inside the text
3. type something
4. see cursor jump to the end

**Expected behavior**

cursor stays where you enter text

**Screenshots**

![2020-09-18 14-07-12 2020-09-18 14_08_12](https://user-images.githubusercontent.com/6270048/93595722-8c37fe80-f9b8-11ea-87da-157e46f6696f.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Safari Tech Preview
 - Version: Release 113 (Safari 14.0.1, WebKit 15610.2.3.1)

**Additional context**

I've seen this problem before, in e.g.:

- https://github.com/facebook/react/issues/955
- https://github.com/facebook/react/issues/14904

**Comment by viljamis** [comment]
@Haroenv Thanks for reporting this! I can confirm that I am able to reproduce this behaviour in Safari. Tried in other browsers as well, but seems like it’s only happening in Safari. / cc @WickyNilliams

**Comment by WickyNilliams** [comment]
I think this is actually fixed as of [this commit](https://github.com/duetds/date-picker/commit/ad0c695efe207c38261e314494737a6567f169ea). I am not able to reproduce now. Can you confirm, and if so, close the issue please @Haroenv?

**Comment by Haroenv** [comment]
Thanks for fixing @wickynilliams!
