### ISSUE TITLE
Build attempt fails due to snapshot mismatch

### ISSUE THREAD

**Issue by Woebin** [duetds/date-picker#18]
**Describe the bug**
Running `npm install` fails when automated testing detects unacceptable differences in the image snapshot diffs.

**To Reproduce**
1. Clone the project
2. Run `npm install`
3. Wait while install process runs

**Expected behavior**
I expected the installation not to fail, and to complete successfully.

**Screenshots**
Console output:
![image](https://user-images.githubusercontent.com/16818848/93604949-69ace200-f9c6-11ea-9e57-24fc238f97f0.png)

Images found in `\date-picker\src\components\duet-date-picker\__image_snapshots__\__diff_output__`:
![duet-date-picker-e-2-e-ts-duet-date-picker-min-max-support-supports-a-max-date-1-diff](https://user-images.githubusercontent.com/16818848/93605197-b42e5e80-f9c6-11ea-8f35-cf7310afd418.png)
![duet-date-picker-e-2-e-ts-duet-date-picker-min-max-support-supports-a-min-date-1-diff](https://user-images.githubusercontent.com/16818848/93605210-b98ba900-f9c6-11ea-9571-eb266ec336a6.png)
![duet-date-picker-e-2-e-ts-duet-date-picker-min-max-support-supports-min-and-max-dates-1-diff](https://user-images.githubusercontent.com/16818848/93605216-bb556c80-f9c6-11ea-860c-b4c645c0bcbf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Version 10.0.17763 Build 17763
 - Browser: n/a
 - Version: Node.js v12.18.3, npm 6.14.6

**Comment by viljamis** [comment]
@Woebin Thanks for reporting! We’re aware of this, but need to ponder a little what to do here. @WickyNilliams good ideas?

**Comment by WickyNilliams** [comment]
I think we should not be running tests on install. I think the `prepublish` hook in package.json runs on install (surprising quirk of npm!). We should change to `prepublishOnly`, which doesn't have this surprising behaviour

**Comment by viljamis** [comment]
Fixed in my latest commit.
