### ISSUE TITLE
localized date incorrectly submitted as part of <form>

### ISSUE THREAD

**Issue by wimdeblauwe** [duetds/date-picker#21]
I am trying to use duet-date-picker with Thymeleaf (server-side rendering). It works as long as I don't use the localization support.

I added this in a `<script>` tag in my page:

```
    const picker = document.querySelector('duet-date-picker');
    const DATE_FORMAT = /^(\d{1,2})\.(\d{1,2})\.(\d{4})$/;

    if (picker) {
        picker.dateAdapter = {
            parse(value = '', createDate) {
                try {
                    console.log('parsing' + value);
                    const matches = value.match(DATE_FORMAT);

                    if (matches) {
                        return createDate(matches[3], matches[2], matches[1]);
                    }
                } catch (err) {
                    console.log(err);
                }
            },
            format(date) {
                console.log('formatting: ' + date);
                return `${date.getDate()}.${date.getMonth() + 1}.${date.getFullYear()}`;
            },
        };
    }
```

I see lot's of `formatting...` statements, but never `parsing...` and also no error in the console.

When I check with dev tools, I see updates to the `value` attribute of `<duet-date-picker>`, but the `value` of the actual `<input>` is not updated. Due to this, my server-side thinks that nothing was selected. For some reason, that does not seem to be an issue when _not_ using the localization support. Am I doing something wrong?

**Comment by WickyNilliams** [comment]
Parsing is only used when typing into the input itself with a keyboard. All values passed as props should be in ISO-8601 format, not your locale. Is that where you've gone wrong?

**Comment by wimdeblauwe** [comment]
What do you mean with "values passed as props"? The `value` of the `<input>` is what Spring will look at when the form is POST'ed to the server. I would think that the component keeps that up to date itself?

**Comment by WickyNilliams** [comment]
I mean even if you are using localisation, you should still pass dates in ISO format:

```
<duet-date-picker value="2020-09-25"></duet-date-picker>
```

Can you confirm you're doing this?

**Comment by wimdeblauwe** [comment]
I am indeed doing this when the page is generated on the server initially. The proper value is shown according to the `format` function. But if I select a different date using the picker and submit the form, then the server receives no value for the `<input>`.

**Comment by WickyNilliams** [comment]
OK, I think the issue title threw me off as it seems unrelated to what you're describing. Could you share some of your code?

**Comment by wimdeblauwe** [comment]
Sure. So I have added the js and css in my `<head>` section:

```
    <script type="module" src="https://cdn.jsdelivr.net/npm/@duetds/date-picker@1.0.1/dist/duet/duet.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@duetds/date-picker@1.0.1/dist/duet/duet.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@duetds/date-picker@1.0.1/dist/duet/themes/default.css"/>
```

The Thymeleaf code that uses the component looks like this:

```
<duet-date-picker th:identifier="${fieldName}"
                          th:value="*{__${fieldName}__}"
                          th:name="${fieldName}"
                          class="w-full sm:text-sm sm:leading-5"
                          th:classappend="${#fields.hasErrors('__${fieldName}__')?'error-border':''}">
        </duet-date-picker>
```

This renders in the browser like this:

![image](https://user-images.githubusercontent.com/1115823/94257673-f22e0400-ff2b-11ea-9872-444d47add57a.png)

You can see that the custom `format` function is being used.

This is the HTML that Chrome dev tools shows:

![image](https://user-images.githubusercontent.com/1115823/94257758-1ab5fe00-ff2c-11ea-84a6-6c39d0f62558.png)

You can see that the `value` has the correct ISO-8601 format.

If I select a different date using the picker, I can see the `value` change to the selected date (in ISO-8601 format).

When I post the form after that, I get a validation error that the value is not present.

If I remove the code to overwrite the `dateAdapter`, then the value is shown to the user in ISO-8601 format:

![image](https://user-images.githubusercontent.com/1115823/94258146-b2b3e780-ff2c-11ea-8275-76cc3842ff93.png)
 
The HTML looks the same to me:

![image](https://user-images.githubusercontent.com/1115823/94258211-cc552f00-ff2c-11ea-816d-5bcc4115eb56.png)

And posting the form works without issues after selecting a different date (or not selecting any date at all).

**Comment by WickyNilliams** [comment]
Having done some investigation, the input _is_ being submitted, but it's being submitted with the localised value. e.g. so in this case you'll get a form submission with `birthday=6.9.2020`. So it probably fails to parse on your server. 

I think a fix for this would be to have a hidden input, which would store the current ISO value and participate in form submission. The text input is then purely for the purpose of display/manual entry

**Comment by wimdeblauwe** [comment]
Yes, that would be great. Is this something that could be fixed on short term? I am writing a book about Thymeleaf and wanted to include an example of using a date picker. I'd love to use this one, but I would need a fix for this, preferably in the coming weeks if that is possible?

**Comment by WickyNilliams** [comment]
I think we should be able to get a fix out this week or next. It won't be a big change on our end.

You might be able to work around it with something like this:

```html
<duet-date-picker name=""></duet-date-picker>
<input type="hidden" name="birthday" />

<script>
  const picker = document.querySelector("duet-date-picker");
  const hidden = document.querySelector(`input[type="hidden"]`);

  picker.dateAdapter = {
    parse(value = "", createDate) {
      try {
        console.log("parsing" + value);
        const matches = value.match(DATE_FORMAT);

        if (matches) {
          return createDate(matches[3], matches[2], matches[1]);
        }
      } catch (err) {
        console.log(err);
      }
    },
    format(date) {
      console.log("formatting: " + date);
      return `${date.getDate()}.${date.getMonth() + 1}.${date.getFullYear()}`;
    },
  };

  picker.addEventListener("duetChange", (e) => {
    hidden.value = e.detail.value
  });
</script>
```

Basically, copy the value on change into a hidden input youtself. But that's a bit of a hack, and is essentially what we'd end up doing behind the scenes

**Comment by wimdeblauwe** [comment]
ok, great. I'll wait for the update. Thanks!

**Comment by WickyNilliams** [comment]
I'm going to edit the issue title to better reflect the problem, hope that's ok!

**Comment by wimdeblauwe** [comment]
@WickyNilliams Any idea when a fix can be released on this?

**Comment by WickyNilliams** [comment]
Sorry, this fell through the net. I'll see if i can get a PR together tomorrow

**Comment by WickyNilliams** [comment]
PR ready, feel free to test @wimdeblauwe and let me know if it works for you :)

**Comment by wimdeblauwe** [comment]
Thanks! How can I get the binaries to test?

**Comment by wimdeblauwe** [comment]
Is this included in the 1.1.0 release? Or can I see release notes somewhere?

**Comment by WickyNilliams** [comment]
Yes, it is included. There's not much by the way of release notes (there is a short changelog in the readme). 

Using this code as an example, you will now _always_ get an ISO date submitted via the form, despite using a British date adapter (omitted for conciseness):

```html
<form>
  <duet-date-picker name="date"></duet-date-picker>
  <button type="submit">Submit</button>
</form>

<script>
  const picker = document.querySelector("duet-date-picker");
  picker.dateAdapter = britishDateAdapter
</script>
```

Hope that helps

**Comment by wimdeblauwe** [comment]
I can confirm it works with version 1.1.0. Thanks for the bugfix!
