### ISSUE TITLE
Safari on iOS trigger unnecessary month picker comes up

### ISSUE THREAD

**Issue by mattdamon108** [duetds/date-picker#23]
**Describe the bug**
When I click the calendar button in Safari or React Native Webview on iOS, the native month picker comes up and hide duetds.

**To Reproduce**
1. connect to the page in Safari or React Native Webview on iOS
2. click the calendar button
3. native month picker comes up after the duetds shows up

**Expected behavior**
The native month picker wouldn't show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/36963424/93951549-9a539980-fd81-11ea-87f9-5d6b5260764e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS 14, iPhone11
 - Browser: safari
 - Version: "@duetds/date-picker": "^1.0.1"

**Comment by viljamis** [comment]
@mattdamon108 As this is the expected behaviour, I’m closing this issue for now.
