### ISSUE TITLE
Plan to support time as well?

### ISSUE THREAD

**Issue by anselmh** [duetds/date-picker#33]
**Describe the solution you'd like**
Hey, is there a plan to support datetime and time formats as well and show a picker for hourse and minutes, seconds (optionally)? If not, feel free to close the issue…

**Comment by WickyNilliams** [comment]
We have no plans to support time. I feel it would complicate the date picker quite a bit. 

I would personally go for the simplest possible option - having a separate component for entering time - whether that be native `<input type="time" />` (probably not great), or two drop downs for hour and minutes. 

Closing but happy to discuss further

**Comment by anselmh** [comment]
> We have no plans to support time. I feel it would complicate the date picker quite a bit.

I totally understand it and it was more the question of what your plans are with the project.

> I would personally go for the simplest possible option - having a separate component for entering time - whether that be native `<input type="time" />` (probably not great), or two drop downs for hour and minutes.

Yeah, that’s what we’re currently doing (type time) but it’s really bad UX-wise and people don’t understand what they should do on Desktop. Mobile UIs are great, unfortunately the Safari, Firefox, Chrome UI on Desktop aren’t… But we were playing around with doing a progressive enhancement component on these fields using a writeable dropdown UI.

Thanks for the feedback and no worries about closing it! :)
