### ISSUE TITLE
Make the datepicker a required field

### ISSUE THREAD

**Issue by wimbschimmelpfennig** [duetds/date-picker#38]
It seems there is no way to set the input to required, is there any workaround or is this on the roadmap?

**Comment by tim-reynolds-thegrommet** [comment]
I have a workaround, I just came here to open an issue about this very thing! Give me a moment..

**Comment by tim-reynolds-thegrommet** [comment]
So this is a hack we put together that checks for the required attribute on the `<duet-date-picker>` tag, and once it sees the input existing below passes the required attribute on to it. It isn't pretty but it is working. 

```

            const limit = 100;
            let count = 0;
            function fixRequired() {
                if(++count >= limit) {
                    /* If something goes wrong, don't try forever. */
                    return;
                }
                const pickerInput = document.querySelector("duet-date-picker[identifier='{{$name}}'] input")
                if(pickerInput instanceof HTMLInputElement) {
                    pickerInput.required = true;
                } else {
                    setTimeout(fixRequired, 500);
                }
            }
            setTimeout(fixRequired, 500);
```

You would need to replace the `{{$name}}` code with your own identifier or modify it to just search for all the duet date pickers. 

So we would also like to ask if there is plan to add `required` functionality. And thank you for the great datepicker.

**Comment by wimbschimmelpfennig** [comment]
@tim-reynolds-thegrommet I did something similiar.

```
$(window).on('load', function() {

    if($('.date-picker-required').length>0)
    {
        $('.date-picker-required input').prop('required', true);
    }
});
```

using jquery ->  window.onload and adding a date-picker-required class to each datepicker where its needed, however this is not a clean solution either.

It would be best if you could pass an input yourself or do something like:
```
<duet-date-picker>
<input type="text" required />
</duet-date-picker>
```

**Comment by martinfjant** [comment]
I've used a hack as well, but for some reason I had to add a delay (even after accounting for the datepicker being mounted).

´´´
/* Hack to add "required" and listener to the date selector */
/* await component mount*/
customElements.whenDefined("duet-date-picker").then(() => {
  /*select the web component */
  const pickers = document.querySelectorAll("duet-date-picker");
  /*Wait some more and change required to true*/
  setTimeout(() => {
    pickers.forEach((picker) => {
      const input = picker.firstChild.firstChild.firstChild;
      input.required = true;
      addValidationToInput(input);
      picker.addEventListener("duetChange", () => debounce(unDisableNext(), 250));
    });
  }, 500);
});
´´´

**Comment by tim-reynolds-thegrommet** [comment]
Definitely seems like this is a feature that the date picker could use.

**Comment by WickyNilliams** [comment]
This should be pretty easy to add. I'll see if I can do it tomorrow

**Comment by WickyNilliams** [comment]
PR here for testing https://github.com/duetds/date-picker/pull/42. Please test and report back :)
