### ISSUE TITLE
Google lighthouse complains that the datepicker uses an eventlistener that is not passive

### ISSUE THREAD

**Issue by martinfjant** [duetds/date-picker#39]
**Describe the bug**
Google lighthouse complains that the datepicker uses an eventlistener that is not passive

**To Reproduce**
1. Use the date picker somewhere
2. Run Google Lighthouse
3. Se warning

**Expected behavior**
Google lighthouse shows no warnings

**Desktop (please complete the following information):**
 - Chrome, latest

**Additional context**
It might be related to https://github.com/ionic-team/stencil/issues/2621

**Comment by WickyNilliams** [comment]
I've not been able to reproduce this. Can you give any more details?

**Comment by martinfjant** [comment]
I'm using the date picker twice on a page; I'm running Lighthouse on the latest Google Chrome on OSX Catilina.
<img width="465" alt="Skärmavbild 2020-10-30 kl  10 32 56" src="https://user-images.githubusercontent.com/16226616/97689213-89dac100-1a9b-11eb-9289-d2fcce33a5e1.png">
<img width="434" alt="Skärmavbild 2020-10-30 kl  10 32 32" src="https://user-images.githubusercontent.com/16226616/97689226-8e06de80-1a9b-11eb-9c33-71c6dd7fdb2d.png">

**Comment by martinfjant** [comment]
It's actually not scroll, but touch listeners. It might not be anything within your control (I'm not very into how stencil works), but I do think it's related to https://github.com/ionic-team/stencil/issues/2621 .

I've tested with all my addons disabled, and the results are the same. Touch start and touch end :(.

I might be able to make a minimal repo that resembles the one we have at work later!

**Comment by martinfjant** [comment]
Using lighthouse on the demo/docs gives me the same error as well. 
<img width="1369" alt="Skärmavbild 2020-11-02 kl  14 05 12" src="https://user-images.githubusercontent.com/16226616/97871247-7d14d200-1d14-11eb-9ff7-b3ad237118bc.png">

**Comment by WickyNilliams** [comment]
So strange that I don't get it! Just to be sure there wasn't something weird going on with my own machine, I ran the test from the google site itself (https://web.dev/measure/) and got this result:

![image](https://user-images.githubusercontent.com/1091390/97871454-71bda880-1d0c-11eb-9175-80b239916560.png)

But we do use touch handlers. It may be possible to move to passive listeners, but i'm not 100% sure as we `preventDefault()` on touchmove

**Comment by martinfjant** [comment]
I ran that version on the code we're using and **I do not get that error in the web.dev version!** Do you use the same version of chrome? Nevertheless, if it's only my local Chrome that complains it won't affect a lot of other people! But it sure is an oddity.

**Comment by WickyNilliams** [comment]
Yes, I'm using that exact version of chrome. Very strange! 

At least for now I will close this issue. In future I may look at adding lighthouse as an automated test of some sort, to prevent any perf regressions. Thanks for reporting
