### ISSUE TITLE
Enhance year display when min and max are used

### ISSUE THREAD

**Issue by sdussaut** [duetds/date-picker#48]
Hello!

Thanks for this project, the picker is really great.

I would like to propose an enhancement to it regarding the display of the year list when range values are used.

The use case is as follows:

- using the picker to pick a birth date within a range of acceptable values (say 1920-2020).
- year list only display 20 entries at a time. To display more I need to select the first one, close the list and then open it again. So the user could easily do this multiple times if she is born in 1954 for example. Which is not quite straightforward and a bit tedious for some users.

To enhance this behaviour, the picker could display all the years within the range only when range values are set (either min, max or both).

Thanks again for this great project!

**Comment by johnantoni** [comment]
Exactly what I need, thanks. When setting a date of birth the 20 entries at a time isn't ideal.

**Comment by WickyNilliams** [comment]
Fixed in `v1.2.0`
