### ISSUE TITLE
Cannot increase the year limit

### ISSUE THREAD

**Issue by johnantoni** [duetds/date-picker#53]
Hi, i'm using the control with Vue and I'm trying to increase the options available in the year picker.

Currently it's only showing ranges from 2020 to 2010.

I tried using the properties min="1990-06-10" and max="2020-07-18" but this had no effect.

Any ideas how to solve this?

<img width="69" alt="Screen Shot 2020-11-19 at 12 08 29 PM" src="https://user-images.githubusercontent.com/15571/99699647-2f140400-2a60-11eb-9da0-bdd1c8668682.png">

**Comment by johnantoni** [comment]
figured it out, setting the `:localization.prop` overrides the min / max parameters

**Comment by WickyNilliams** [comment]
Could you share how your code worked originally when you opened the issue, and what your code looked like by the time you closed the issue? The localization prop shouldn't affect min/max dates, so curious what you issue you hit here

**Comment by johnantoni** [comment]
@WickyNilliams  Actually I thought it was that but then I realized date picker is showing 20 year options at a time.

Is there any way this branch could be merged in so the year list can be scrollable?

https://github.com/duetds/date-picker/pull/49

**Comment by WickyNilliams** [comment]
Fixed in #49, released in `v1.2.0`
