### ISSUE TITLE
Working without JS

### ISSUE THREAD

**Issue by long-lazuli** [duetds/date-picker#54]
**Is your feature request related to a problem? Please describe.**
When JS is disabled, it doesn't work

**Describe the solution you'd like**
This should be a native datePicker, till it can be enhanced by JS.

**Comment by WickyNilliams** [comment]
How do you suggest supporting this? Being a web component, it is entirely dependent on JavaScript

**Comment by long-lazuli** [comment]
well, I don't know :)
I'm not well versed in web-component, I'd just like to use this component.
```
<input type="date" />
<img "visually-hidden" error="convertToWebComponent(this.previousElementSibling, 'duet-date-picker')" src="" />
```

**Comment by WickyNilliams** [comment]
Ah ok! This can be done on your side with some progressive enhancement.

Something like this should do:


```html
<form>
  <label>
	choose date:
	<input id="date" type="date" />
  </label>
</form>

<script>
  function convertToWebComponent() {
    const input = document.querySelector("#date")
    const component = document.createElement("duet-date-picker")

	// swap out native element for duet picker
	input.insertAdjacentElement("beforebegin", component)
	input.remove()
  }

  // see: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined
  customElements.whenDefined("duet-date-picker").then(convertToWebComponent)
</script>
```

You could modify this to your suiting - maybe it should loop over native inputs and replace each one? It could also copy any attributes over (`name`, `required`, `id` etc) so it's a 1:1 replacement. But hopefully this is enough to get you started 🙂 

I'll close the issue now
