### ISSUE TITLE
Question: is it possible to add multiple date pickers on the same page?

### ISSUE THREAD

**Issue by martinlex** [duetds/date-picker#63]
**Is your feature request related to a problem? Please describe.**
When doing ranges of dates (from/to):
Is it possible to add multiple date pickers on the same page?

**Describe the solution you'd like**
I would like to add multiple date pickers on the same page.

**Comment by WickyNilliams** [comment]
Yes it's possible. For example, the docs have many instances of the picker on the same page. 

If you're building a range picker, here's some rough code to get you started https://github.com/duetds/date-picker/issues/4#issuecomment-704994834
