### ISSUE TITLE
List of requirements?

### ISSUE THREAD

**Issue by jasonday** [duetds/date-picker#66]
> Our team working on Duet Design System couldn’t find an existing date picker that would’ve ticked all the requirements we had for accessibility (supporting WCAG 2.1 as well as we can)

Do you have a list of what those requirements are?

**Comment by WickyNilliams** [comment]
We needed something that was:

* lightweight in terms of filesizs 
* keyboard accessible
* screen reader accessible 
* not tied to a specific framework
* supported internationalisation
* themeable enough to make it look like a native part of the design system

I couldn't really find any existing pickers that hit all  those points. So despite the initial apprehension, we decided to build our own

**Comment by WickyNilliams** [comment]
Does that answer your question?
