### ISSUE TITLE
onClose Event

### ISSUE THREAD

**Issue by chardin1** [duetds/date-picker#71]
**Is your feature request related to a problem? Please describe.**
It would be very useful to have a `duetClose` event we can listen to. This would allow us to know when the modal is closed via keyboard "close" button.

**Describe alternatives you've considered**
I've tried to use the `duetBlur` event but that seems to be fired when the modal opens so it's not a good flag for when it has been closed.

**Comment by WickyNilliams** [comment]
Closed via #73
