### ISSUE TITLE
How can I change the display values of month number picker in android Date picker

### ISSUE THREAD

**Issue by asthagarg2428** [duetds/date-picker#75]
NOT A BUG THOUGH, its a doubt!
My requirement is that the month number picker should show values like 01,02,03... but android's default date picker shows months like Jan, Feb,Mar...(when locale is India) and 1,2,3.. in countries like korea.
My requirement is to have month display values as 01,02..12.
How can I achieve this?? If through reflection, then how because I'm unable to do so even after multiple tries?
Any help?

**Comment by WickyNilliams** [comment]
Can you explain a little more please? I'm not sure I understand, but you can control how months are displayed using the `monthNames` field of the `localization` object property. See here https://github.com/duetds/date-picker#localization

**Comment by WickyNilliams** [comment]
Closing due to lack of response. Please let me know if you are still having issues
