### ISSUE TITLE
Selecting a month then selecting days from another month seen in the calendar.

### ISSUE THREAD

**Issue by paaljoachim** [duetds/date-picker#96]
**Is your feature request related to a problem? Please describe.**

One can see days from other months but not select them. First one has to switch months and then select the days.

**Describe the solution you'd like**

![Screen Shot 2021-08-27 at 23 03 33](https://user-images.githubusercontent.com/5323259/131188487-b23985f4-d5ad-44db-8cf5-f544c23ab477.jpg)

Above here we see 1-5 days in September. It would be nice to be able to click one of these days in September and have the calendar select the day and at the same time switch months.

**Comment by paaljoachim** [comment]
Hi @WickyNilliams Nick!
Dependencies are updated and it works nicely.
Thank you!

**Comment by WickyNilliams** [comment]
Awesome, glad to hear it
